"""
Ralph Wiggum - Autonomous Task Processing Loop
Gold Tier AI Employee - Keeps working until all tasks are complete

"Marge, I'm gonna be a Ralph Wiggum!"
"""

import os
import sys
import shutil
from datetime import datetime
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Configuration from .env
VAULT_PATH = os.getenv("VAULT_PATH", r"C:\Users\Iqra Traders\Documents\AI_Employee_Vault")

# Paths
NEEDS_ACTION_FOLDER = os.path.join(VAULT_PATH, "Needs_Action")
DONE_FOLDER = os.path.join(VAULT_PATH, "Done")
PLANS_FOLDER = os.path.join(VAULT_PATH, "Plans")
LOGS_FOLDER = os.path.join(VAULT_PATH, "Logs")
DASHBOARD_FILE = os.path.join(VAULT_PATH, "Dashboard.md")

# Safety limits
MAX_ITERATIONS = 10


def ensure_directories():
    """Create necessary directories if they don't exist"""
    os.makedirs(NEEDS_ACTION_FOLDER, exist_ok=True)
    os.makedirs(DONE_FOLDER, exist_ok=True)
    os.makedirs(PLANS_FOLDER, exist_ok=True)
    os.makedirs(LOGS_FOLDER, exist_ok=True)


def get_pending_tasks():
    """Get list of pending task files in Needs_Action folder"""
    if not os.path.exists(NEEDS_ACTION_FOLDER):
        return []
    
    tasks = []
    for filename in os.listdir(NEEDS_ACTION_FOLDER):
        filepath = os.path.join(NEEDS_ACTION_FOLDER, filename)
        if os.path.isfile(filepath):
            tasks.append({
                "name": filename,
                "path": filepath
            })
    
    return sorted(tasks, key=lambda x: x["name"])


def read_task_file(filepath):
    """Read the content of a task file"""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            return f.read()
    except Exception as e:
        print(f"  ⚠️  Warning: Could not read {filepath}: {e}")
        return ""


def create_plan(task_name, task_content):
    """Create a plan file for the task in Plans folder"""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    plan_filename = f"PLAN_{task_name}"
    if plan_filename.endswith(".md"):
        plan_filename = plan_filename.replace(".md", "")
    plan_filename = f"{plan_filename}.md"
    
    plan_path = os.path.join(PLANS_FOLDER, plan_filename)
    
    # Extract task type from filename or content
    task_type = "General Task"
    if "EMAIL" in task_name.upper():
        task_type = "Email Processing"
    elif "WHATSAPP" in task_name.upper():
        task_type = "WhatsApp Processing"
    elif "SOCIAL" in task_name.upper():
        task_type = "Social Media"
    elif "INVOICE" in task_name.upper():
        task_type = "Invoice Creation"
    elif "TEST" in task_name.upper():
        task_type = "Test Task"
    
    plan_content = f"""---
type: task_plan
created: {datetime.now().isoformat()}
task: {task_name}
status: completed
---

# Task Plan: {task_name}

## Task Type
{task_type}

## Original Task Content
{task_content[:500]}{'...' if len(task_content) > 500 else ''}

## Actions Taken
- ✅ Task analyzed
- ✅ Plan created
- ✅ Task moved to Done folder
- ✅ Dashboard updated

## Completion Status
Completed by Ralph Wiggum Loop at {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

---
Generated by Ralph Wiggum AI Employee v1.0
"""
    
    try:
        with open(plan_path, "w", encoding="utf-8") as f:
            f.write(plan_content)
        return True
    except Exception as e:
        print(f"  ⚠️  Warning: Could not create plan: {e}")
        return False


def move_to_done(task_name):
    """Move task file from Needs_Action to Done folder"""
    src = os.path.join(NEEDS_ACTION_FOLDER, task_name)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    # Add timestamp to filename when moving to Done
    base_name = task_name
    if base_name.endswith(".md"):
        base_name = base_name[:-3]
    dst_name = f"{base_name}_{timestamp}.md"
    dst = os.path.join(DONE_FOLDER, dst_name)
    
    try:
        shutil.move(src, dst)
        return True
    except Exception as e:
        print(f"  ⚠️  Warning: Could not move file: {e}")
        return False


def update_dashboard(tasks_processed):
    """Update Dashboard.md with task count"""
    total_processed = tasks_processed
    
    # Try to read existing dashboard
    existing_count = 0
    if os.path.exists(DASHBOARD_FILE):
        try:
            with open(DASHBOARD_FILE, "r", encoding="utf-8") as f:
                content = f.read()
                # Try to find existing count
                if "Total Tasks Completed:" in content:
                    for line in content.split("\n"):
                        if "Total Tasks Completed:" in line:
                            try:
                                existing_count = int(line.split(":")[1].strip())
                            except:
                                existing_count = 0
        except:
            existing_count = 0
    
    new_count = existing_count + tasks_processed
    
    dashboard_content = f"""---
type: dashboard
updated: {datetime.now().isoformat()}
---

# AI Employee Dashboard

## Quick Stats
- **Total Tasks Completed:** {new_count}
- **Last Update:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
- **Status:** ✅ Active

## Today's Activity
- Tasks Processed: {tasks_processed}

## System Status
- Ralph Wiggum Loop: ✅ Active
- Task Processing: ✅ Operational

---
Generated by Syed Ahsan AI Employee v1.0
"""
    
    try:
        with open(DASHBOARD_FILE, "w", encoding="utf-8") as f:
            f.write(dashboard_content)
        return True
    except Exception as e:
        print(f"  ⚠️  Warning: Could not update dashboard: {e}")
        return False


def create_log(tasks_processed, iteration, duration):
    """Create a log entry for this loop iteration"""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    log_file = os.path.join(LOGS_FOLDER, f"ralph_loop_{timestamp}.log")
    
    log_content = f"""---
type: ralph_wiggum_loop
timestamp: {datetime.now().isoformat()}
iteration: {iteration}
status: completed
---

## Ralph Wiggum Loop - Iteration {iteration}

### Summary
- Tasks Processed: {tasks_processed}
- Duration: {duration:.2f} seconds
- Status: Completed

### Actions
- Scanned Needs_Action folder
- Processed pending tasks
- Created plans in Plans folder
- Moved tasks to Done folder
- Updated Dashboard

---
Generated by Ralph Wiggum AI Employee v1.0
"""
    
    try:
        with open(log_file, "w", encoding="utf-8") as f:
            f.write(log_content)
        return True
    except Exception as e:
        print(f"  ⚠️  Warning: Could not create log: {e}")
        return False


def create_test_tasks():
    """Create 3 sample test tasks in Needs_Action folder"""
    ensure_directories()
    
    test_tasks = [
        ("TEST_ralph_1.md", """---
type: test_task
created: """ + datetime.now().isoformat() + """
priority: normal
---

## Test Task 1
This is a test task for Ralph Wiggum loop.
Task: Send welcome email to new client.

Action Required:
- Draft welcome email
- Send to client@example.com
"""),
        ("TEST_ralph_2.md", """---
type: test_task
created: """ + datetime.now().isoformat() + """
priority: high
---

## Test Task 2
This is a test task for Ralph Wiggum loop.
Task: Create invoice for March services.

Action Required:
- Create invoice in Odoo
- Amount: PKR 50,000
- Client: ABC Corporation
"""),
        ("TEST_ralph_3.md", """---
type: test_task
created: """ + datetime.now().isoformat() + """
priority: normal
---

## Test Task 3
This is a test task for Ralph Wiggum loop.
Task: Schedule social media posts for next week.

Action Required:
- Create 3 LinkedIn posts
- Schedule using scheduler
""")
    ]
    
    created = 0
    for filename, content in test_tasks:
        filepath = os.path.join(NEEDS_ACTION_FOLDER, filename)
        try:
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(content)
            created += 1
        except Exception as e:
            print(f"Warning: Could not create test task {filename}: {e}")
    
    print(f"\n📋 Created {created} test tasks in Needs_Action folder")
    return created


def ralph_wiggum_loop(create_test=False):
    """
    Main Ralph Wiggum autonomous loop
    Processes all tasks in Needs_Action until empty or max iterations
    """
    start_time = datetime.now()
    
    print("\n" + "="*60)
    print("🤖 Ralph Wiggum Loop Starting...")
    print("📋 Checking for pending tasks...")
    print("="*60)
    
    ensure_directories()
    
    # Create test tasks if requested
    if create_test:
        create_test_tasks()
    
    total_tasks_processed = 0
    iteration = 0
    
    while iteration < MAX_ITERATIONS:
        iteration += 1
        iteration_start = datetime.now()
        
        print(f"\n🔄 Iteration {iteration}/{MAX_ITERATIONS}")
        
        # Get pending tasks
        pending_tasks = get_pending_tasks()
        task_count = len(pending_tasks)
        
        if task_count == 0:
            print("\n✅ TASK_COMPLETE - All tasks processed!")
            break
        
        print(f"📊 Found {task_count} pending task(s)")
        
        # Process each task
        processed_this_iteration = 0
        for i, task in enumerate(pending_tasks, 1):
            print(f"\n  Processing task {i} of {task_count}: {task['name']}")
            
            # Read task content
            task_content = read_task_file(task["path"])
            
            # Create plan
            if create_plan(task["name"], task_content):
                print(f"    ✅ Plan created")
            
            # Move to Done
            if move_to_done(task["name"]):
                print(f"    ✅ Moved to Done folder")
                processed_this_iteration += 1
                total_tasks_processed += 1
        
        # Update dashboard
        update_dashboard(processed_this_iteration)
        print(f"\n  📊 Dashboard updated")
        
        # Create log
        iteration_duration = (datetime.now() - iteration_start).total_seconds()
        create_log(processed_this_iteration, iteration, iteration_duration)
        
        # Check if we should continue
        remaining = len(get_pending_tasks())
        print(f"\n  📊 Remaining tasks: {remaining}")
        
        if remaining == 0:
            print("\n✅ TASK_COMPLETE - All tasks processed!")
            break
    
    # Calculate total time
    total_duration = (datetime.now() - start_time).total_seconds()
    
    # Final summary
    print("\n" + "="*60)
    print("📊 RALPH WIGGUM LOOP - FINAL SUMMARY")
    print("="*60)
    print(f"  Total Tasks Processed: {total_tasks_processed}")
    print(f"  Iterations Used: {iteration}")
    print(f"  Time Taken: {total_duration:.2f} seconds")
    print(f"  Dashboard: Updated")
    
    if iteration >= MAX_ITERATIONS:
        remaining_tasks = len(get_pending_tasks())
        print(f"\n⚠️  Max iterations reached ({MAX_ITERATIONS})")
        print(f"    Remaining tasks: {remaining_tasks}")
        print(f"    Run the loop again to process remaining tasks")
    else:
        print(f"\n✅ All tasks completed successfully!")
    
    print("="*60)
    
    return {
        "total_processed": total_tasks_processed,
        "iterations": iteration,
        "duration": total_duration,
        "success": iteration < MAX_ITERATIONS
    }


def main():
    """Main function"""
    # Check for test flag
    create_test = "--test" in sys.argv or "-t" in sys.argv
    
    if create_test:
        print("\n🧪 TEST MODE: Creating test tasks...")
    
    # Run the Ralph Wiggum loop
    result = ralph_wiggum_loop(create_test=create_test)
    
    # Exit code based on success
    if result["success"]:
        sys.exit(0)
    else:
        sys.exit(1)


if __name__ == "__main__":
    main()
