"""
Scheduler for AI Employee
Runs scheduled tasks automatically.
Silver Tier Feature
"""

import os
import time
import re
from datetime import datetime, timedelta
from pathlib import Path
from dotenv import load_dotenv
import schedule

# Load environment variables
load_dotenv(r"C:\Users\Iqra Traders\Documents\ai_employee\.env")

# Configuration
VAULT_PATH = r"C:\Users\Iqra Traders\Documents\AI_Employee_Vault"
NEEDS_ACTION_FOLDER = os.path.join(VAULT_PATH, "Needs_Action")
DONE_FOLDER = os.path.join(VAULT_PATH, "Done")
LOGS_FOLDER = os.path.join(VAULT_PATH, "Logs")

# Track last run times
last_daily_briefing = None
last_overload_check = None
last_ceo_briefing = None


def get_md_files_in_folder(folder_path, days_back=1):
    """Get all .md files in a folder, optionally filtered by date."""
    if not os.path.exists(folder_path):
        return []
    
    files = []
    cutoff_date = datetime.now() - timedelta(days=days_back)
    
    for filename in os.listdir(folder_path):
        if filename.endswith('.md'):
            filepath = os.path.join(folder_path, filename)
            try:
                file_time = datetime.fromtimestamp(os.path.getmtime(filepath))
                if file_time >= cutoff_date:
                    files.append(filename)
            except Exception:
                files.append(filename)
    
    return files


def parse_frontmatter(filepath):
    """Parse the frontmatter from a markdown file."""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
        
        frontmatter_match = re.search(r'---\s*\n(.*?)\n---\s*\n', content, re.DOTALL)
        if not frontmatter_match:
            return {}, content
        
        frontmatter = frontmatter_match.group(1)
        body = content[frontmatter_match.end():].strip()
        
        metadata = {}
        for line in frontmatter.split('\n'):
            if ':' in line:
                key, value = line.split(':', 1)
                metadata[key.strip()] = value.strip()
        
        return metadata, body
    except Exception:
        return {}, ""


def create_daily_briefing():
    """Create daily morning briefing at 8:00 AM."""
    global last_daily_briefing
    
    now = datetime.now()
    current_date = now.strftime("%Y-%m-%d")
    current_datetime = now.strftime("%Y-%m-%d %H:%M:%S")
    display_date = now.strftime("%A, %B %d, %Y")
    
    print("\n" + "=" * 70)
    print("📰 RUNNING: Daily Morning Briefing")
    print("=" * 70)
    print(f"  📅 Date: {display_date}")
    print(f"  ⏰ Time: {current_datetime}")
    
    # Count pending tasks
    pending_files = get_md_files_in_folder(NEEDS_ACTION_FOLDER, days_back=7)
    pending_count = len(pending_files)
    
    # Count completed tasks today
    done_files_today = get_md_files_in_folder(DONE_FOLDER, days_back=1)
    done_today_count = len(done_files_today)
    
    # Count completed tasks yesterday
    done_files_yesterday = []
    if os.path.exists(DONE_FOLDER):
        for filename in os.listdir(DONE_FOLDER):
            if filename.endswith('.md'):
                filepath = os.path.join(DONE_FOLDER, filename)
                try:
                    file_time = datetime.fromtimestamp(os.path.getmtime(filepath))
                    yesterday = datetime.now() - timedelta(days=1)
                    if file_time.date() == yesterday.date():
                        done_files_yesterday.append(filename)
                except Exception:
                    continue
    
    # Create briefing content
    briefing_content = f"""---
type: briefing
generated: {current_datetime}
status: pending
---
## Good Morning! Daily Briefing - {display_date}

### Pending Tasks
"""
    
    if pending_files:
        briefing_content += "\n"
        for filename in pending_files[:10]:  # List first 10
            briefing_content += f"- [ ] {filename}\n"
        if len(pending_files) > 10:
            briefing_content += f"- ... and {len(pending_files) - 10} more\n"
    else:
        briefing_content += "\n✅ No pending tasks!\n"
    
    briefing_content += f"""
### Tasks Completed Yesterday
"""
    
    if done_files_yesterday:
        briefing_content += "\n"
        for filename in done_files_yesterday[:10]:  # List first 10
            briefing_content += f"- [x] {filename}\n"
        if len(done_files_yesterday) > 10:
            briefing_content += f"- ... and {len(done_files_yesterday) - 10} more\n"
    else:
        briefing_content += "\nNo tasks completed yesterday.\n"
    
    briefing_content += f"""
### Summary
- Total Pending: {pending_count}
- Total Done Today: {done_today_count}
- Status: 🟢 AI Employee Active

---
*Generated by AI Employee Scheduler*
"""
    
    # Write briefing file
    briefing_path = os.path.join(VAULT_PATH, "DAILY_BRIEFING.md")
    
    try:
        with open(briefing_path, "w", encoding="utf-8") as f:
            f.write(briefing_content)
        
        print(f"\n  ✅ Daily Briefing created: DAILY_BRIEFING.md")
        print(f"  📊 Pending Tasks: {pending_count}")
        print(f"  ✅ Done Today: {done_today_count}")
        print(f"  ✅ Done Yesterday: {len(done_files_yesterday)}")
        
        last_daily_briefing = now
        
    except Exception as e:
        print(f"  ❌ Error creating briefing: {e}")
    
    print("=" * 70)


def check_overload():
    """Check every 30 minutes if there are too many pending tasks."""
    global last_overload_check
    
    now = datetime.now()
    
    print("\n" + "=" * 70)
    print("⚠️  RUNNING: Overload Check")
    print("=" * 70)
    
    # Count pending tasks
    pending_files = get_md_files_in_folder(NEEDS_ACTION_FOLDER, days_back=7)
    pending_count = len(pending_files)
    
    print(f"  📊 Pending Tasks: {pending_count}")
    
    # Check if overload (more than 5 pending)
    if pending_count > 5:
        print(f"  ⚠️  OVERLOAD DETECTED: {pending_count} pending tasks!")
        
        # Create alert file
        alert_content = f"""---
type: alert
generated: {now.strftime('%Y-%m-%d %H:%M:%S')}
priority: high
status: pending
---
## ⚠️  TASK OVERLOAD ALERT

### Current Status
- Pending Tasks: {pending_count}
- Threshold: 5 tasks
- Status: OVERLOADED

### Message
Too many pending tasks - please review!

### Recommended Actions
- [ ] Review pending tasks in Needs_Action folder
- [ ] Prioritize urgent items
- [ ] Delegate or defer non-critical tasks
- [ ] Move completed items to Done folder

---
*Generated by AI Employee Overload Monitor*
"""
        
        alert_path = os.path.join(NEEDS_ACTION_FOLDER, "ALERT_overload.md")
        
        try:
            with open(alert_path, "w", encoding="utf-8") as f:
                f.write(alert_content)
            
            print(f"  ✅ Alert created: ALERT_overload.md")
            
        except Exception as e:
            print(f"  ❌ Error creating alert: {e}")
    else:
        print("  ✅ Task count within normal limits")
    
    last_overload_check = now
    print("=" * 70)


def create_ceo_briefing():
    """Create weekly CEO briefing on Monday at 9:00 AM."""
    global last_ceo_briefing
    
    now = datetime.now()
    current_datetime = now.strftime("%Y-%m-%d %H:%M:%S")
    week_number = now.isocalendar()[1]
    display_date = now.strftime("%A, %B %d, %Y")
    
    print("\n" + "=" * 70)
    print("📊 RUNNING: Weekly CEO Briefing")
    print("=" * 70)
    print(f"  📅 Date: {display_date}")
    print(f"  📆 Week: {week_number}")
    
    # Count completed tasks this week
    done_files_week = get_md_files_in_folder(DONE_FOLDER, days_back=7)
    done_week_count = len(done_files_week)
    
    # Count logs this week
    log_files_week = get_md_files_in_folder(LOGS_FOLDER, days_back=7)
    log_week_count = len(log_files_week)
    
    # List pending items
    pending_files = get_md_files_in_folder(NEEDS_ACTION_FOLDER, days_back=7)
    
    # Create briefing content
    briefing_content = f"""---
type: ceo_briefing
generated: {current_datetime}
week: {week_number}
---
## Monday Morning CEO Briefing

### This Week Summary

**Completed Tasks This Week:** {done_week_count}

**Actions Logged:** {log_week_count}

"""
    
    # Add summary of actions from logs
    if log_files_week:
        briefing_content += "### Recent Actions\n"
        log_files_sample = log_files_week[:5]
        for log_file in log_files_sample:
            log_path = os.path.join(LOGS_FOLDER, log_file)
            metadata, _ = parse_frontmatter(log_path)
            action_type = metadata.get('type', 'unknown')
            briefing_content += f"- {action_type}: {log_file}\n"
        if len(log_files_week) > 5:
            briefing_content += f"- ... and {len(log_files_week) - 5} more actions\n"
    
    briefing_content += f"""
### Pending Items

"""
    
    if pending_files:
        briefing_content += f"**Total Pending:** {len(pending_files)}\n\n"
        for filename in pending_files[:10]:
            filepath = os.path.join(NEEDS_ACTION_FOLDER, filename)
            metadata, _ = parse_frontmatter(filepath)
            task_type = metadata.get('type', 'task')
            briefing_content += f"- [{task_type}] {filename}\n"
        if len(pending_files) > 10:
            briefing_content += f"- ... and {len(pending_files) - 10} more\n"
    else:
        briefing_content += "✅ No pending items!\n"
    
    briefing_content += f"""
### AI Employee Status

- 🟢 All systems operational
- Watchers: Gmail ✅ WhatsApp ✅ File System ✅
- Scheduler: Active ✅
- Approval System: Ready ✅

---
*Generated by AI Employee Scheduler*
"""
    
    # Write briefing file
    briefing_path = os.path.join(VAULT_PATH, "MONDAY_CEO_BRIEFING.md")
    
    try:
        with open(briefing_path, "w", encoding="utf-8") as f:
            f.write(briefing_content)
        
        print(f"\n  ✅ CEO Briefing created: MONDAY_CEO_BRIEFING.md")
        print(f"  📊 Completed This Week: {done_week_count}")
        print(f"  📋 Actions Logged: {log_week_count}")
        print(f"  ⏳ Pending Items: {len(pending_files)}")
        
        last_ceo_briefing = now
        
    except Exception as e:
        print(f"  ❌ Error creating CEO briefing: {e}")
    
    print("=" * 70)


def show_schedule():
    """Display the upcoming schedule on startup."""
    now = datetime.now()
    
    # Calculate next daily briefing (8:00 AM)
    next_daily = now.replace(hour=8, minute=0, second=0, microsecond=0)
    if now >= next_daily:
        next_daily += timedelta(days=1)
    
    # Calculate next overload check (next 30 minute mark)
    next_overload = now.replace(second=0, microsecond=0)
    if next_overload.minute >= 30:
        next_overload += timedelta(hours=1)
        next_overload = next_overload.replace(minute=0)
    elif next_overload.minute > 0:
        next_overload = next_overload.replace(minute=30)
    
    # Calculate next CEO briefing (next Monday 9:00 AM)
    days_until_monday = (7 - now.weekday()) % 7
    if days_until_monday == 0 and now.hour >= 9:
        days_until_monday = 7
    next_ceo = now.replace(hour=9, minute=0, second=0, microsecond=0) + timedelta(days=days_until_monday)
    
    print("\n" + "=" * 70)
    print("📅 SCHEDULE OVERVIEW")
    print("=" * 70)
    print(f"\n  📰 Next Daily Briefing:     {next_daily.strftime('%Y-%m-%d %H:%M')} (8:00 AM daily)")
    print(f"  ⚠️  Next Overload Check:    {next_overload.strftime('%Y-%m-%d %H:%M')} (Every 30 minutes)")
    print(f"  📊 Next CEO Briefing:       {next_ceo.strftime('%Y-%m-%d %H:%M')} (Monday 9:00 AM)")
    print("\n" + "=" * 70)


def run_overload_check():
    """Wrapper for overload check to handle exceptions."""
    try:
        check_overload()
    except Exception as e:
        print(f"\n❌ Error in overload check: {e}")


def run_daily_briefing():
    """Wrapper for daily briefing to handle exceptions."""
    try:
        create_daily_briefing()
    except Exception as e:
        print(f"\n❌ Error in daily briefing: {e}")


def run_ceo_briefing():
    """Wrapper for CEO briefing to handle exceptions."""
    try:
        create_ceo_briefing()
    except Exception as e:
        print(f"\n❌ Error in CEO briefing: {e}")


def main():
    """Main function to run the scheduler."""
    print("=" * 70)
    print("🤖 AI Employee - Scheduler (Silver Tier)")
    print("=" * 70)
    print("\nAutomated Task Scheduling System")
    print("=" * 70)
    
    # Ensure vault folders exist
    for folder in [VAULT_PATH, NEEDS_ACTION_FOLDER, DONE_FOLDER, LOGS_FOLDER]:
        if not os.path.exists(folder):
            print(f"📁 Creating folder: {folder}")
            os.makedirs(folder)
    
    print(f"\n📂 Vault Path: {VAULT_PATH}")
    
    # Show schedule
    show_schedule()
    
    # Schedule tasks
    print("\n📋 SCHEDULING TASKS...")
    print("=" * 70)
    
    # Daily briefing at 8:00 AM
    schedule.every().day.at("08:00").do(run_daily_briefing)
    print("  ✅ Daily Briefing:    Every day at 8:00 AM")
    
    # Overload check every 30 minutes
    schedule.every(30).minutes.do(run_overload_check)
    print("  ✅ Overload Check:    Every 30 minutes")
    
    # CEO briefing every Monday at 9:00 AM
    schedule.every().monday.at("09:00").do(run_ceo_briefing)
    print("  ✅ CEO Briefing:      Every Monday at 9:00 AM")
    
    print("=" * 70)
    
    # Run initial checks
    print("\n🔄 Running initial checks...")
    run_overload_check()
    
    print("\n" + "=" * 70)
    print("🚀 SCHEDULER STARTED")
    print("=" * 70)
    print("\nPress Ctrl+C to stop...\n")
    
    # Main loop
    while True:
        try:
            # Run pending scheduled tasks
            schedule.run_pending()
            
            # Sleep briefly to reduce CPU usage
            time.sleep(1)
            
        except KeyboardInterrupt:
            print("\n\n" + "=" * 70)
            print("⏹️  Scheduler stopped by user")
            print("=" * 70)
            break
        except Exception as e:
            print(f"\n❌ Unexpected error: {e}")
            time.sleep(5)


if __name__ == "__main__":
    main()
